### ISSUE TITLE
different serial monitor rates

### ISSUE THREAD

**Issue by petemango** [benymng/4FUN#8]
The two sensors that we have, namely the ultrasonic distance sensor and the accelerometer share differing baud rates on the serial monitor. That being said, the two sensors only are able to work independently of each-other and cannot co-exist in the same ardunio environment. Attempts of changing one of the sensors to use hardwareSerial has been unsuccessful. :)

**Comment by probablyalexzhu** [comment]
FIXED. simply remove a sensor 6head
